### ISSUE TITLE
Regex doesn't work please help

### ISSUE THREAD

**Issue by Nosterx** [inkarkat/vim-SyntaxRange#11]
I wanna highlight sql in python file written like this
```python
    SQL = """
        SELECT * FROM somwhere
    """
```
I tried this regex `autocmd FileType python call SyntaxRange#IncludeEx('start="^ *\w = ["]{3}" end="^[ ]{4}["]{3}"', 'sql')` which works perfectly on regex101.com but doesnt work in vim.

**Comment by inkarkat** [comment]
There are several small problems with your regexp:

* Vim's default escaping rules are a bit different; repetition must be written as `\{3}` ([`:help /\{`](https://vimhelp.appspot.com/pattern.txt.html#%2F%5C%7B)). Alternatively, you could switch the entire regexp to _very nomagic_ ([`:help /\v`](https://vimhelp.appspot.com/pattern.txt.html#%2F%5Cv)) by prepending a `\v`.
* Due to the `\w =`, only single letter variables would match, it needs to be `\w\+ =` to match the `SQL = """` from your example.
* You can work around the conflicting use of the double quotes via `["]`, but it is more common to simply use a different separator for the entire pattern; e.g. `/.../`.
* Instead of hard-coding spaces (and the fixed amount of 4 in the end pattern), I would make this more general by using `\s\+`.

````
call SyntaxRange#IncludeEx('start=/^ *\w\+ = "\{3}/ end=/^ \{4}"\{3}/', 'sql')
````

For me, this still matches the whole inner SQL as `sqlString`, not the desired separately-colored SQL keywords. I tried to avoid this via some `ms=e+1` ([`:help :syn-pattern-offset`](https://vimhelp.appspot.com/syntax.txt.html#%3Asyn-pattern-offset)) and variations of that, but failed so far in my attempts. As described in the plugin's limitations, the success of the inclusion depends on the original syntaxes, and can be tricky.
