### ISSUE TITLE
generic syntax rule

### ISSUE THREAD

**Issue by zoranbosnjak** [inkarkat/vim-SyntaxRange#12]
From the example on the project page... If I enable:

```vim
:call SyntaxRange#Include('@begin=c@', '@end=c@', 'c', 'NonText')
```
... I can use:

```
@begin=c@
int i = 42;
@end=c@
```
To use it on another syntax (e.g. python), a new `:call SyntaxRange...` is required, where "c" is replaced with "python". Is there a way to abstract over "c" from the example above, such that it works for any syntax? For example, to specify a single rule, something like:

```vim
:call SyntaxRange#Include('@begin=<syn>@', '@end=<syn>@', syn, 'NonText')
```

The "c" example above remains unchanged, but I could also use:

```
@begin=python@...
@begin=bash@...
...
```

**Comment by inkarkat** [comment]
The plugin is just a convenient wrapper over Vim's `:syntax include` command; because of that, each syntax needs to be explicitly imported.

You can simplify the repetitive invocation a bit via a `for` loop:

    for syntax in ['c', 'python', 'sh']
        call SyntaxRange#Include(printf('@begin=%s@', syntax), printf('@end=%s@', syntax), syntax, 'NonText')
    endfor

This should be fine for a few syntaxes (like, say, a dozen or so), but it might noticeably slow down Vim if you attempt to handle more than that. In that case, the loop could check whether the buffer contains the particular syntax region (`if search(printf('@begin=%s@', syntax))`) and only import those that are found (but then it would only work with existing regions, not those added later, unless you re-scan on each buffer save via `:autocmd BufWritePost <buffer>`).
