### ISSUE TITLE
Literal newline matches null instead of newline in startPattern

### ISSUE THREAD

**Issue by user202729** [inkarkat/vim-SyntaxRange#13]
**Describe the bug**

New line characters can't be matched in startPattern.

**How to Reproduce**

Run `call SyntaxRange#Include("HTML(\n", ')', 'html')`

**Expected Behavior**

In a buffer with

```
" HTML(
"<div> </div> )
```

the content inside should be highlighted.

Instead, it highlights buffer with content for example

```
" HTML(^@<div></div>)
```

------

It's possible to "fix" the issue by passing literal backslash character to the function, however the behavior is quite surprising given that the vim command

```	
syntax region synIncludeHtml  keepend start="HTML(\n" end=')' containedin=ALL contains=@synIncludeHtml
```

matches newline characters.

It's best to either give error on literal `\n` or replace them with the pattern that matches newline. Null characters can still be matched with the corresponding regex or real null character (... didn't test).

**Comment by inkarkat** [comment]
Nice observation, and great report; thanks for that!

Due to its history, Vim sometimes has unexpected inconsistencies in its data model, and that's what's happening here.

In the equivalent `:syntax` Ex command, the delimiters around the `{pattern}` can be any two identical characters (cp. [`:help :syn-pattern`](https://vimhelp.appspot.com/syntax.txt.html#%3Asyn-pattern)).

    syntax region synIncludeHtml  keepend start="HTML(\n" end=')' containedin=ALL contains=@synIncludeHtml

In your example, you've chosen double quotes for the start and single quotes for the end pattern, but it could be anything (e.g. `start=/HTML(\n/ end=@)@`)

In the plugin invocation, however, the arguments are of Vim _String type_ and as such double-quoted contents interpret contained escape sequences, and `\n` turns into a literal newline which in the Vim buffer then matches the null character (another peculiarity of Vim). So the equivalent Ex command is rather

    syntax region synIncludeHtml  keepend start='HTML(^@' end=')' containedin=ALL contains=@synIncludeHtml

or (written with explicit String interpolation through `:execute`):

    execute "syntax region synIncludeHtml  keepend start='HTML(\n' end=')' containedin=ALL contains=@synIncludeHtml"

And that explains the behavior. If you use single quotes (recommended as the default quoting style by the [vim-vint linter](https://github.com/Vimjas/vint)), the issue goes away:

    call SyntaxRange#Include('HTML(\n', ')', 'html')

In fact, because your example just uses the newline to assert an end-of line match, you can simply use `$` instead (`\n` is only needed if you need to match across two lines).

    call SyntaxRange#Include('HTML($', ')', 'html')

**Comment by inkarkat** [comment]
A plugin warning might indeed prevent users from falling into this trap; however, as it is just a thin convenience wrapper around `:syn include` and users eventually have to learn the idiosyncrasies of Vim for effective use, anyway, I'm reluctant to complicate the code with such.
