### ISSUE TITLE
Ignore indentation for syntax highlighting of a range (because here-doc breaks highlighting)

### ISSUE THREAD

**Issue by MaxGyver83** [inkarkat/vim-SyntaxRange#19]
**Motivation**

I use vim-SyntaxRange to highlight bash scripts embedded in Azure DevOps pipeline definition files (YAML). This works great in general but the syntax highlighting of the embedded bash code breaks whenever here-doc strings are used:

![2024-01-16 20 56 10 576x222 Region](https://github.com/inkarkat/vim-SyntaxRange/assets/13970628/f212022c-8f3a-44ef-b9cf-aaaf1c9eb373)

The problem is that the `EOF` in line 7 is indented (like the whole bash script).

`~/.vim/after/syntax/yaml/SyntaxInclude.vim`:

```vim
call SyntaxRange#Include('^ *-\? \(script\|bash\): |', 'condition:\|displayName:\|log_globs:', 'bash')
```

Example code:

```yaml
- job: "Demo job"
  steps:
  - bash: |
      echo "Creating temporary bash script."
      cat << 'EOF' > /tmp/my-script.bash
      echo "Running my-script.bash"
      EOF
      docker exec -it ubuntu /tmp/my-script.bash
    displayName: demo
```

**Request and Purpose**

I'm wondering if it would be possible to let vim ignore the indentation of the bash block (lines 4-8). Maybe vim-SyntaxRange can request vim to syntax highlight only columns 7 till end? Then the `EOF` would appear to be at the start of the line and the syntax highlighting wouldn't break.

**Alternatives**

As a workaround I have tried adding the here-doc string as a separate (nested) bash block:

```vim
call SyntaxRange#Include('^ *cat \?<<.*', '^ *EOF', 'bash')
```

![image](https://github.com/inkarkat/vim-SyntaxRange/assets/13970628/ed146705-3140-4112-9364-0197899fa188)

In this case, line 8 is highlighted correctly but line 6 is not highlighted as bash. Is this the result of nesting bash blocks?

Anyway, I think it's not easy to get this pattern right to match any here-doc string.

**Comment by inkarkat** [comment]
Your (really good) reproducible example matches the `shHereDoc05` syntax group of the `sh.vim` syntax file.  This syntax group is defined as follows:

```
" Here Documents: {{{1
"  (modified by Felipe Contreras)
" =========================================
ShFoldHereDoc syn region shHereDoc matchgroup=shHereDoc01 start="<<\s*\z([^ \t|>]\+\)"		matchgroup=shHereDoc01 end="^\z1$"	contains=@shDblQuoteList
ShFoldHereDoc syn region shHereDoc matchgroup=shHereDoc02 start="<<-\s*\z([^ \t|>]\+\)"		matchgroup=shHereDoc02 end="^\t*\z1$"	contains=@shDblQuoteList
ShFoldHereDoc syn region shHereDoc matchgroup=shHereDoc03 start="<<\s*\\\z([^ \t|>]\+\)"	matchgroup=shHereDoc03 end="^\z1$"
ShFoldHereDoc syn region shHereDoc matchgroup=shHereDoc04 start="<<-\s*\\\z([^ \t|>]\+\)"	matchgroup=shHereDoc04 end="^\t*\z1$"
ShFoldHereDoc syn region shHereDoc matchgroup=shHereDoc05 start="<<\s*'\z([^']\+\)'"		matchgroup=shHereDoc05 end="^\z1$"
[...]
```

The problem is in the `end="^\z1$"` part; it enforces a match of the heredoc delimiter directly at the beginning of the line. The SyntaxRange plugin is just a simple convenience wrapper around Vim's syntax include mechanism, so there's no easy way around it.

Ideally, Vim's [`:syn-include`](https://vimhelp.appspot.com/syntax.txt.html#%3Asyn-include) would be extended so that e.g. a `startcol=N` could be passed, and Vim would then ignore any text before that column. (But that would have to consider not just `^`, but also multi-line matches via `\n`, explicit column matching via `\%c`, and so on. Really hairy to implement correctly.)

Alternatively, every syntax plugin could offer a `b:effectiveStartCol` variable, but this is just as complex, and the (already very long) syntax script would need a lot of ugly `:execute` metaprogramming.

So neither is likely to happen :-( The shell syntax in particular has some heredoc variants that do support tab-indented heredoc delimiters, e.g. `shHereDoc02`. So a slight modification of the syntax works right out of the box (`^I` = tab):

```
^I^Icat <<- EOF > /tmp/my-script.bash
^I^I^Iecho "Running my-script.bash"
^I^I^Iecho "Creating temporary bash script."
^I^IEOF
```

Unfortunately, YAML doesn't support tab indentation :-( Bummer.

---

Your workaround attempt with the separate bash block doesn't work because the plugin's begin and end syntax definitions include the shell syntax, and `sh.vim`'s heredoc patterns still match on those block borders, preventing a correct match of the actual Bash syntax. A `:syntax clear shHereDoc` would get rid of that syntax definition, and you could obtain all possible heredoc patterns from `$VIMRUNTIME/syntax/sh.vim`'s definition, but this indeed is a very hacky solution.

I personally see these setups as an 80% "best effort" solution; large code blocks in YAML mostly are a code smell in itself, better moved to a separate file (if possible).

**Comment by MaxGyver83** [comment]
OK, bad luck for me. Thank you for your detailed answer!

**Comment by MaxGyver83** [comment]
> The problem is in the `end="^\z1$"` part; it enforces a match of the heredoc delimiter directly at the beginning of the line. 

Can't I simply override this rule, replacing `^\z` with `^ *`?

`~/.vim/after/syntax/sh/sh.vim`:

```vim
syn region shHereDoc matchgroup=shHereDoc05 start="<<\s*'\z([^']\+\)'"		matchgroup=shHereDoc05 end="^ *1$"
```

This didn't work. But maybe only some detail is wrong. Could this work in principle?

**Comment by inkarkat** [comment]
You need to keep the `\z1` intact; it's a reference to the heredoc delimiter (e.g. `EOF`); cp. [`:help /\z(`](https://vimhelp.appspot.com/syntax.txt.html#%2F%5Cz%28).

So something like `end="^ *\z1$"` might work.

If you use something like `~/.vim/after/syntax/sh.vim`, the override would then also apply to plain shell scripts (so mistakenly indented heredocs would now be highlighted as if they were correct, but that may be a reasonable trade-off). To make this fully correct, you'd need to introduce a boolean flag, or maybe use `main_syntax` to detect the syntax inclusion.

**Comment by MaxGyver83** [comment]
> If you use something like `~/.vim/after/syntax/sh.vim`, the override would then also apply to plain shell scripts (so mistakenly indented heredocs would now be highlighted as if they were correct, but that may be a reasonable trade-off). 

That's okay for me.

> You need to keep the `\z1` intact; it's a reference to the heredoc delimiter (e.g. `EOF`); cp. [`:help /\z(`](https://vimhelp.appspot.com/syntax.txt.html#%2F%5Cz%28).

Oops. Thank you!

> So something like `end="^ *\z1$"` might work.

Indeed, this works BUT only in regular bash script files:

![image](https://github.com/inkarkat/vim-SyntaxRange/assets/13970628/d3717d44-a779-4a2e-aa37-79390965770c)

(This file is named `heredoc.bash` but both `&ft` and `&syntax` equal `sh`.)

It doesn't work with vim-SyntaxRange:

![image](https://github.com/inkarkat/vim-SyntaxRange/assets/13970628/af91cac5-9bfd-49ed-a620-4626b7e8cf32)

(No matter if I use `sh` or `bash` in `call SyntaxRange#Include(...)`.)

Do you know why it's different in both screenshots/files?

**Comment by MaxGyver83** [comment]
Nevermind. It turned out that it works as expected also with vim-SyntaxRange when I override the heredoc rule in `~/.vim/after/syntax/sh.vim` instead of `~/.vim/after/syntax/sh/sh.vim`. No idea why it matters. But it works.

**Comment by inkarkat** [comment]
Ah, great! `~/.vim/after/syntax/sh.vim` is the correct location for this - you wouldn't use further subdirectories in the _after_ directory. (Except maybe to override something that is in `~/.vim/syntax/sh/*.vim` itself.)

BTW, the [SyntaxAttr.vim - Show syntax highlighting attributes of character under cursor](https://www.vim.org/scripts/script.php?script_id=383) plugin helps with troubleshooting these problems; it shows which syntax group is active under the cursor. (I maintain an [extended fork](https://github.com/inkarkat/SyntaxAttr.vim).)

**Comment by MaxGyver83** [comment]
> Ah, great! `~/.vim/after/syntax/sh.vim` is the correct location for this - you wouldn't use further subdirectories in the _after_ directory. (Except maybe to override something that is in `~/.vim/syntax/sh/*.vim` itself.)

OK, good to know. But why are vim-SyntaxRange configurations in `~/.vim/after/syntax/{filetype}/SyntaxInclude.vim` and not in `~/.vim/after/syntax/{filetype}.vim`?

> BTW, the [SyntaxAttr.vim - Show syntax highlighting attributes of character under cursor](https://www.vim.org/scripts/script.php?script_id=383) plugin helps with troubleshooting these problems; it shows which syntax group is active under the cursor. (I maintain an [extended fork](https://github.com/inkarkat/SyntaxAttr.vim).)

Thank you! I have just installed your fork.

**Comment by inkarkat** [comment]
> But why are vim-SyntaxRange configurations in `~/.vim/after/syntax/{filetype}/SyntaxInclude.vim` and not in `~/.vim/after/syntax/{filetype}.vim`?

The latter is for the user's own personalizations; a plugin shouldn't occupy (or even override) that spot. Today that's less of an issue as many people use the _pack plugin_ mechanism or a package manager, but plugins just got unpacked directly into `~/.vim` in the past.

**Comment by MaxGyver83** [comment]
I see. Thank you!
