### ISSUE TITLE
issue when "end" is at the same time the "start" of another group

### ISSUE THREAD

**Issue by cdluminate** [inkarkat/vim-SyntaxRange#6]
Hi, I like this script very much. However my demand is that the "end" of a snippt is at the same time the "start" of another snippet. For example:

```
#!/bin/sh
set -e
echo "alsdkfasldkf"

^ python
import os, sys
print('hello')
^
^ cpp
int main(void) {
return 0;
}
^
^ control
Source: example
Section: asdfasdf
^
```

And I source this vim script:
```vim
source ./SyntaxRange.vim
call SyntaxRange#IncludeEx('start="\^ cpp" end="\^.*"', 'cpp')
call SyntaxRange#IncludeEx('start="\^ python" end="\^.*"', 'python')
call SyntaxRange#IncludeEx('start="\^ control" end="\^.*"', 'debcontrol')
```

The syntax highlighting will break if I remove the `^` in line 8 and 13 from the original txt file. Could you please give me some pointers on this problem?

**Comment by inkarkat** [comment]
Remember that the plugin is just a convenience wrapper around `:syntax range`, so this is a general Vim syntax problem. In order to have _overlapping_ start and end ranges, each character must be actually matched by one pattern or the other, but **not both**. It is possible to _assert_ matches with lookahead / lookbehind, though, and that's the key to attacking the problem.

So one way to solve this is to just assert the `^` character ending the range, without matching it, through a _positive loohahead_ (`\@=`). The region end will be empty, but the `^` character is still asserted to be there:

    call SyntaxRange#IncludeEx('start="\^ cpp" end="\^\@="', 'cpp')
    call SyntaxRange#IncludeEx('start="\^ python" end="\^\@="', 'python')
    call SyntaxRange#IncludeEx('start="\^ control" end="\^\@="', 'debcontrol')

An alternative keeps a non-empty end (the trailing `.*` is useless there, anyway, I dropped it to allow a match by another region start). In the region start, assert the `^` before with a _positive lookbehind assertion_ (`\@<=`):

    call SyntaxRange#IncludeEx('start="\^\@<= cpp" end="\^"', 'cpp')
    call SyntaxRange#IncludeEx('start="\^\@<= python" end="\^"', 'python')
    call SyntaxRange#IncludeEx('start="\^\@<= control" end="\^"', 'debcontrol')

**Comment by inkarkat** [comment]
I've you intend to write (and publish!) a separate Vim syntax plugin, I would recommend to directly use `:syntax include` and `:syntax region`. It's a little bit more code to write, but your users will appreciate not having to download another dependency. The plugin is meant to be a convenience for quickly setting up regions on demand, or maybe automatically as part of one's personal customizations.

**Comment by cdluminate** [comment]
Thank you very much!
